/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as FocusSessionsRouteImport } from './routes/focus-sessions'
import { Route as MasterGridRouteImport } from './routes/master-grid'
import { Route as MeetingNotesRouteImport } from './routes/meeting-notes'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as TaskPlannerRouteImport } from './routes/task-planner'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusSessionsRoute = FocusSessionsRouteImport.update({
  id: '/focus-sessions',
  path: '/focus-sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterGridRoute = MasterGridRouteImport.update({
  id: '/master-grid',
  path: '/master-grid',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingNotesRoute = MeetingNotesRouteImport.update({
  id: '/meeting-notes',
  path: '/meeting-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskPlannerRoute = TaskPlannerRouteImport.update({
  id: '/task-planner',
  path: '/task-planner',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assets': typeof AssetsRoute
  '/focus-sessions': typeof FocusSessionsRoute
  '/master-grid': typeof MasterGridRoute
  '/meeting-notes': typeof MeetingNotesRoute
  '/research': typeof ResearchRoute
  '/task-planner': typeof TaskPlannerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assets': typeof AssetsRoute
  '/focus-sessions': typeof FocusSessionsRoute
  '/master-grid': typeof MasterGridRoute
  '/meeting-notes': typeof MeetingNotesRoute
  '/research': typeof ResearchRoute
  '/task-planner': typeof TaskPlannerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assets': typeof AssetsRoute
  '/focus-sessions': typeof FocusSessionsRoute
  '/master-grid': typeof MasterGridRoute
  '/meeting-notes': typeof MeetingNotesRoute
  '/research': typeof ResearchRoute
  '/task-planner': typeof TaskPlannerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/assets'
    | '/focus-sessions'
    | '/master-grid'
    | '/meeting-notes'
    | '/research'
    | '/task-planner'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/assets'
    | '/focus-sessions'
    | '/master-grid'
    | '/meeting-notes'
    | '/research'
    | '/task-planner'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/assets'
    | '/focus-sessions'
    | '/master-grid'
    | '/meeting-notes'
    | '/research'
    | '/task-planner'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AssetsRoute: typeof AssetsRoute
  FocusSessionsRoute: typeof FocusSessionsRoute
  MasterGridRoute: typeof MasterGridRoute
  MeetingNotesRoute: typeof MeetingNotesRoute
  ResearchRoute: typeof ResearchRoute
  TaskPlannerRoute: typeof TaskPlannerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus-sessions': {
      id: '/focus-sessions'
      path: '/focus-sessions'
      fullPath: '/focus-sessions'
      preLoaderRoute: typeof FocusSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-grid': {
      id: '/master-grid'
      path: '/master-grid'
      fullPath: '/master-grid'
      preLoaderRoute: typeof MasterGridRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting-notes': {
      id: '/meeting-notes'
      path: '/meeting-notes'
      fullPath: '/meeting-notes'
      preLoaderRoute: typeof MeetingNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task-planner': {
      id: '/task-planner'
      path: '/task-planner'
      fullPath: '/task-planner'
      preLoaderRoute: typeof TaskPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AssetsRoute: AssetsRoute,
  FocusSessionsRoute: FocusSessionsRoute,
  MasterGridRoute: MasterGridRoute,
  MeetingNotesRoute: MeetingNotesRoute,
  ResearchRoute: ResearchRoute,
  TaskPlannerRoute: TaskPlannerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
